[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Tốc độ upload
upload_speed = 921600
monitor_speed = 115200

; Thư viện cần thiết
lib_deps =
    lvgl/lvgl@^8.3.0
    adafruit/Adafruit ILI9341@^1.6.0
    adafruit/Adafruit GFX Library@^1.11.9
    mikalhart/TinyGPSPlus@^1.0.3

; Build flags
build_flags =
    -D LV_CONF_SKIP=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D LV_COLOR_DEPTH=16
    -D LV_COLOR_16_SWAP=1
    -D LV_MEM_SIZE=49152
    -D LV_USE_ARC=1
    -D LV_USE_LABEL=1
    -D LV_USE_LOG=0
    -D LV_FONT_MONTSERRAT_10=1
    -D LV_FONT_MONTSERRAT_12=1
    -D LV_FONT_MONTSERRAT_14=1
    -D LV_FONT_MONTSERRAT_28=1
    -D LV_FONT_MONTSERRAT_48=1
