[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Tốc độ upload
upload_speed = 921600
monitor_speed = 115200

; Thư viện cần thiết
lib_deps =
    lvgl/lvgl@^8.3.0
    bodmer/TFT_eSPI@^2.5.0
    mikalhart/TinyGPSPlus@^1.0.3

; Build flags cho màn hình GC9A01 tròn 3.5"
build_flags =
    -D LV_CONF_SKIP=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D LV_COLOR_DEPTH=16
    -D LV_MEM_SIZE=49152
    -D LV_USE_ARC=1
    -D LV_USE_LABEL=1
    -D LV_USE_LOG=0
    -D LV_FONT_MONTSERRAT_10=1
    -D LV_FONT_MONTSERRAT_12=1
    -D LV_FONT_MONTSERRAT_14=1
    -D LV_FONT_MONTSERRAT_28=1
    -D LV_FONT_MONTSERRAT_48=1
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=10
    -D TFT_DC=9
    -D TFT_RST=8
    -D TFT_BL=46
    -D TFT_BACKLIGHT_ON=1
    -D SPI_FREQUENCY=40000000
    -D SPI_READ_FREQUENCY=20000000
